### ISSUE TITLE
用户界面设计

### ISSUE THREAD

**Issue by StevenRCE0** [io-club/IMS-Frontend#6]

**Comment by HHX0924** [comment]
ok'




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 下午4:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [io-club/IMS-Frontend] 用户界面设计 (Issue #6)





 
Assigned #6 to @HHX0924.
